services:
  web:
    image: odoo:14.0
    container_name: web-odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./startup.sh:/startup.sh
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: db-odoo
    env_file:
      - .env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
